# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clarence Beaulo Pearson III
email: clarence.pearson3@gmail.com
description: I am Clarence B Pearson III, Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clarencebeaulo.appspot.com" # the base hostname & protocol for your site
github_username:  cpearson3

# Build settings
sass:
  load_paths:
    - _sass
    - bower_components/bootsmooth/src/scss
exclude: ['bower_components']
include: ['_pages']
markdown: kramdown

